[package]
name = "domecoon"
version = "0.1.0-alpha"
authors = ["Bourgond Aries <macocio@gmail.com>"]

[dependencies]
acon = "0.5.1"
clippy = { version = "0.0.67", optional = true }

[features]
default=[]

